Big Keymap Restructure
UltimateHackingKeyboard/firmware pull request #18
Opened 2016-12-12 19:17 UTC by algernon

This changes the keymap layout to be as described in #17, and updates the default layout to follow. (Also adds the missing Space and Mod keys on the two keys below the bottom row)

The layout itself was considerably simplified by introducing a few local macros to hide some of the uglier details.

Also includes #16, rebased and slightly redone, on top of the restructuring.

Quick tests show that at least the `MOD` layer is working, as does the base.

2016-12-12 21:27 UTC, mondalaci requested changes

2016-12-12 21:27 UTC, mondalaci commented on right/src/default_layout.c
> +#define L(l) {.type = UHK_KEY_LAYER, .layer = { .target = LAYER_ID_ ## l }}
Would you please rather not use these macros? I understand that they make the code shorter but it'd be great to be able to see the keymap structure as it is. The reusability of the macros shouldn't be a significant benefit either  because we will only define the factory keymap in the firmware. All the other keymaps will live in the EEPROM, serialized by Agent.

2016-12-12 21:27 UTC, mondalaci commented on right/src/default_layout.c
> +#define TRNS {.type = UHK_KEY_TRANSPARENT}
Would you please not use this type? It isn't one of the key actions supported by Agent.

2016-12-12 21:27 UTC, mondalaci commented on right/src/default_layout.c
> +#define Key_NoKey { .raw = 0 }
I can't see the purpose of the `raw` member. How about adding a none action to `uhk_key_t` based on our official type and removing `raw`? The outer union type of `uhk_key_t` could be removed, leaving only the inner struct.

2016-12-12 21:27 UTC, mondalaci commented on right/src/default_layout.c
> +KEYBOARD_LAYOUT(defaultKeyboardLayout)= {
`CurrentKeymap` would be a better name because we'll always overwrite this keymap with the current one. Its initial content just happens to be the factory keymap.

It'd also be worth not to use a macro here. The reason is because we won't define another keymap anywhere, so it's not like we'll reuse the macro.

2016-12-12 21:27 UTC, mondalaci commented on right/src/default_layout.c
> +            S(7_AND_AMPERSAND), S(8_AND_ASTERISK), S(9_AND_OPENING_PARENTHESIS), S(0_AND_CLOSING_PARENTHESIS), S(MINUS_AND_UNDERSCORE), S(EQUAL_AND_PLUS), S(BACKSPACE),
1 key action per line would read very nicely, especially when expanding key actions.

2016-12-12 21:27 UTC, mondalaci commented on right/src/keyboard_layout.c
> +static uint8_t prevLeftKeyStates[KEY_STATE_COUNT];
Ideally, we shouldn't have different variables on a per module basis but store both the left and right previous key states in an array of modules, similar to the keymap.

2016-12-12 21:34 UTC, algernon commented on right/src/default_layout.c
> +#define L(l) {.type = UHK_KEY_LAYER, .layer = { .target = LAYER_ID_ ## l }}
Sure thing. They were mostly there to help me while translating the structure to the new format. Will expand them.

2016-12-12 21:34 UTC, algernon commented on right/src/default_layout.c
> +#define TRNS {.type = UHK_KEY_TRANSPARENT}
It's a hack, kind of, to make it possible to not repeat the layer switchers on the target layer too. But I guess I can just repeat it, doesn't matter.

2016-12-12 21:34 UTC, algernon commented on right/src/default_layout.c
> +#define Key_NoKey { .raw = 0 }
That works too, yes. `.raw` comes from an earlier idea, when I was trying to push everything within 16 bits, and would have used it for some funky tricks. It is, as you correctly spotted, unnecessary by now.

Will drop it, thanks for the note!

2016-12-12 21:34 UTC, algernon commented on right/src/default_layout.c
> +KEYBOARD_LAYOUT(defaultKeyboardLayout)= {
ACK, drop macro, rename variable.

2016-12-13 13:49 UTC, mondalaci commented
All good, thank you for the great work!

2016-12-13 13:50 UTC, merged